/**
 * @file    mpconfigport.h
 * @brief   MicroPython port renesas-ra8 配置文件
 * @note    不要定义 MICROPY_MIN_USE_CORTEX_CPU
 */

#define MICROPY_HW_BOARD_NAME       "CPKCOR-RA8P1"
#define MICROPY_HW_MCU_NAME         "RA8P1"

#define MICROPY_HW_I2C1_SCL         BSP_IO_PORT_05_PIN_12
#define MICROPY_HW_I2C1_SDA         BSP_IO_PORT_05_PIN_11

#define MICROPY_HW_I2C2_SCL         BSP_IO_PORT_05_PIN_15
#define MICROPY_HW_I2C2_SDA         BSP_IO_PORT_05_PIN_14

#define MICROPY_HW_SPI0_MISO        BSP_IO_PORT_07_PIN_00
#define MICROPY_HW_SPI0_MOSI        BSP_IO_PORT_07_PIN_01
#define MICROPY_HW_SPI0_SCK         BSP_IO_PORT_07_PIN_02

#define MICROPY_HW_SPI1_MISO        BSP_IO_PORT_01_PIN_00
#define MICROPY_HW_SPI1_MOSI        BSP_IO_PORT_01_PIN_01
#define MICROPY_HW_SPI1_SCK         BSP_IO_PORT_01_PIN_02

#define MICROPY_HW_SCI1_RXD         BSP_IO_PORT_04_PIN_01
#define MICROPY_HW_SCI1_SCK         BSP_IO_PORT_04_PIN_02
#define MICROPY_HW_SCI1_TXD         BSP_IO_PORT_04_PIN_00

#define MICROPY_HW_SCI2_RXD         BSP_IO_PORT_08_PIN_02
#define MICROPY_HW_SCI2_SCK         BSP_IO_PORT_08_PIN_03
#define MICROPY_HW_SCI2_TXD         BSP_IO_PORT_08_PIN_01

#define MICROPY_HW_SCI4_RXD         BSP_IO_PORT_04_PIN_14
#define MICROPY_HW_SCI4_SCK         BSP_IO_PORT_07_PIN_08
#define MICROPY_HW_SCI4_TXD         BSP_IO_PORT_04_PIN_15

#define MICROPY_HW_SCI5_RXD         BSP_IO_PORT_11_PIN_02
#define MICROPY_HW_SCI5_SCK         BSP_IO_PORT_11_PIN_04
#define MICROPY_HW_SCI5_TXD         BSP_IO_PORT_11_PIN_03

#define MICROPY_HW_SCI6_RXD         BSP_IO_PORT_12_PIN_13
#define MICROPY_HW_SCI6_SCK         BSP_IO_PORT_12_PIN_12
#define MICROPY_HW_SCI6_TXD         BSP_IO_PORT_12_PIN_14

#define MICROPY_HW_SCI8_RXD         BSP_IO_PORT_08_PIN_06
#define MICROPY_HW_SCI8_SCK         BSP_IO_PORT_05_PIN_13
#define MICROPY_HW_SCI8_TXD         BSP_IO_PORT_08_PIN_05

#define MICROPY_LONGINT_IMPL        (MICROPY_LONGINT_IMPL_MPZ)
#define MICROPY_FLOAT_IMPL          (MICROPY_FLOAT_IMPL_DOUBLE)

#ifndef MICROPY_HW_ENABLE_RNG
#define MICROPY_HW_ENABLE_RNG		1
#endif

#ifndef MICROPY_HW_ENABLE_RTC
#define MICROPY_HW_ENABLE_RTC       1
#endif

#define MICROPY_PY_THREAD           0
